// =============================================================================
// DATA UTAMA APLIKASI QIRA'AH
// =============================================================================
const appData = {

    // =========================================================================
    // MATERI MUTHALAAH
    // =========================================================================
    materi: {
        kelas2: [
            {
                id: "k2-1",
                title: "الحَرِيقُ",
                titleTrans: { id: "Kebakaran", en: "The Fire" },
                text: `كَانَ مُحَمَّدٌ نَائِمًا فِي فِرَاشِهِ وَالسَّاعَةُ عَشْرٌ. وَاللَّيْلُ كُلُّهُ ظَلَامٌ وَبَرْدٌ. وَفَجْأَةً سَمِعَ صَوْتًا عَالِيًا فَهَبَّ مِنَ النَّوْمِ. وَفَتَحَ الشُّبَّاكَ فَرَأَى الدَّارَ الْمُجَاوِرَةَ تَشْتَعِلُ. وَخَرَجَ وَصَرَخَ : الْحَرِيقُ ! الْحَرِيقُ ! فَاسْتَيْقَظَ الْجِيرَانُ وَجَاءُوا بِالْمَاءِ حَتَّى أَطْفَأُوا النَّارَ.`,
                translation: `Muhammad sedang tidur di kasurnya pada pukul sepuluh. Malam itu gelap gulita dan dingin. Tiba-tiba ia mendengar suara keras lalu terbangun dari tidurnya. Ia membuka jendela dan melihat rumah tetangga sedang terbakar. Ia keluar dan berteriak: Kebakaran! Kebakaran! Para tetangga pun terbangun dan datang membawa air hingga berhasil memadamkan api.`,
                kosakataPenting: [
                    { kata: "فِرَاشِهِ", ar: "مكانُ النوم، السرير", id: "Kasurnya / Tempat Tidurnya", en: "His bed" },
                    { kata: "ظَلَامٌ", ar: "الظلامُ: عَدَمُ الضِّيَاءِ", id: "Kegelapan", en: "Darkness" },
                    { kata: "فَجْأَةً", ar: "بَغْتَةً، دُوْنَ تَوَقُّعٍ", id: "Tiba-tiba", en: "Suddenly" },
                    { kata: "الشُّبَّاكَ", ar: "النَّافِذَةُ، فَتْحَةٌ فِي الجِدَار", id: "Jendela", en: "The window" },
                    { kata: "تَشْتَعِلُ", ar: "تَحْتَرِقُ، يَشْتَعِلُ: تُوقَدُ النَّارُ فِيهِ", id: "Terbakar / Menyala", en: "Burning / Ablaze" },
                    { kata: "أَطْفَأُوا", ar: "أَخْمَدُوا النَّارَ وَأَزَالُوا لَهَبَهَا", id: "Memadamkan (mereka)", en: "They extinguished" }
                ],
                kuis: [
                    {
                        type: "mcq", id: "k2-1-q1",
                        question: "فِي أَيِّ سَاعَةٍ كَانَ مُحَمَّدٌ نَائِمًا؟",
                        options: ["فِي السَّاعَةِ الثَّامِنَةِ", "فِي السَّاعَةِ الْعَاشِرَةِ", "فِي السَّاعَةِ الثَّانِيَةَ عَشَرَ", "فِي السَّاعَةِ التَّاسِعَةِ"],
                        answer: 1
                    },
                    {
                        type: "mcq", id: "k2-1-q2",
                        question: "مَاذَا رَأَى مُحَمَّدٌ حِيْنَ فَتَحَ الشُّبَّاكَ؟",
                        options: ["رَأَى الشَّارِعَ مُظْلِمًا", "رَأَى جَارَهُ يَلْعَبُ", "رَأَى الدَّارَ الْمُجَاوِرَةَ تَشْتَعِلُ", "رَأَى الْمَطَرَ يَنْزِلُ"],
                        answer: 2
                    },
                    {
                        type: "mcq", id: "k2-1-q3",
                        question: "مَاذَا فَعَلَ الْجِيرَانُ بَعْدَ أَنْ صَرَخَ مُحَمَّدٌ؟",
                        options: ["ذَهَبُوا إِلَى بُيُوتِهِم", "جَاءُوا بِالْمَاءِ حَتَّى أَطْفَأُوا النَّارَ", "اتَّصَلُوا بِالشُّرْطَةِ", "نَامُوا وَلَمْ يَسْمَعُوا"],
                        answer: 1
                    },
                    {
                        type: "mcq", id: "k2-1-q4",
                        question: "مَا مَعْنَى كَلِمَةِ «تَشْتَعِلُ» فِي هَذِهِ الْقِصَّةِ؟",
                        options: ["تَسْقُطُ", "تَحْتَرِقُ", "تَضِيءُ", "تُطْفَأُ"],
                        answer: 1
                    },
                    {
                        type: "mcq", id: "k2-1-q5",
                        question: "مَا الصِّفَةُ الَّتِي وُصِفَ بِهَا اللَّيْلُ فِي الْقِصَّةِ؟",
                        options: ["حَارٌّ وَمُشْمِسٌ", "ظَلَامٌ وَبَرْدٌ", "هَادِئٌ وَجَمِيلٌ", "مُضِيءٌ وَمَطِيرٌ"],
                        answer: 1
                    },
                    {
                        type: "essay", id: "k2-1-q6",
                        question: "مَاذَا تَعَلَّمْتَ مِنْ هَذِهِ الْقِصَّةِ عَنْ أَهَمِّيَّةِ التَّعَاوُنِ بَيْنَ الْجِيرَانِ؟ اُكْتُبْ إِجَابَتَكَ بِاللُّغَةِ الْعَرَبِيَّةِ أَوِ الْإِنْدُوْنِيسِيَّةِ.",
                        keywords: ["تعاون", "مساعدة", "جار", "نار", "أطفأ", "membantu", "kerjasama", "tetangga", "api", "tolong"]
                    },
                    { type: "mufradat", id: "k2-1-q7", question: "مَا مَعْنَى «فِرَاشِهِ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Jendela (النَّافِذَة)", "Tempat Tidur / Kasurnya (السَّرِير)", "Bantal (الوِسَادَة)", "Selimut (الغِطَاء)"], answer: 1 },
                    { type: "mufradat", id: "k2-1-q8", question: "اخْتَرِ الْمَعْنَى الصَّحِيحَ لِكَلِمَةِ «تَشْتَعِلُ»:", options: ["تَسْقُطُ — Jatuh", "تَنَامُ — Tidur", "تَحْتَرِقُ — Terbakar / Menyala", "تَبْكِي — Menangis"], answer: 2 },
                    { type: "mufradat", id: "k2-1-q9", question: "«فَجْأَةً» تَعْنِي بِالْإِنْدُوْنِيسِيَّةِ:", options: ["Perlahan-lahan", "Tiba-tiba", "Setelah lama", "Oleh karena itu"], answer: 1 }
                ]
            },
            {
                id: "k2-2",
                title: "الشَّرُّ بِالشَّرِّ",
                titleTrans: { id: "Kejahatan Dibalas Kejahatan", en: "Evil Repaid with Evil" },
                text: `كَانَ وَلَدٌ فَقِيرٌ جَالِسًا فِي الطَّرِيقِ يَأْكُلُ خُبْزًا. فَرَأَى كَلْبًا نَائِمًا عَلَى بُعْدٍ. فَأَخَذَ حَجَرًا وَرَمَاهُ عَلَيْهِ. فَنَبَحَ الْكَلْبُ وَعَضَّهُ. فَبَكَى الْوَلَدُ وَقَالَ : أَوْجَعَنِي الْكَلْبُ ! فَقَالَ لَهُ شَيْخٌ : وَأَنْتَ آذَيْتَهُ أَوَّلًا يَا وَلَدِي، فَالشَّرُّ بِالشَّرِّ.`,
                translation: `Seorang anak miskin sedang duduk di jalan memakan roti. Ia melihat seekor anjing tidur di kejauhan. Ia mengambil batu dan melemparkannya ke arah anjing itu. Anjing itu pun menggonggong dan menggigitnya. Anak itu pun menangis dan berkata: Anjing itu menyakitiku! Berkatalah seorang syekh kepadanya: Kamu sendiri yang menyakitinya lebih dulu, wahai anakku. Kejahatan dibalas dengan kejahatan.`,
                kosakataPenting: [
                    { kata: "حَجَرًا", ar: "الْحَجَرُ: جِسْمٌ صَلِبٌ مِنَ الأَرْض", id: "Batu", en: "A stone" },
                    { kata: "رَمَاهُ", ar: "قَذَفَهُ وَأَلْقَاهُ مِنْ يَدِهِ", id: "Melemparkannya", en: "He threw it" },
                    { kata: "نَبَحَ", ar: "صَوَّتَ الكَلْبُ: صَوْتُهُ الْمَعْرُوف", id: "Menggonggong", en: "Barked" },
                    { kata: "عَضَّهُ", ar: "أَمْسَكَهُ بِأَسْنَانِهِ وَعَقَرَهُ", id: "Menggigitnya", en: "Bit him" },
                    { kata: "آذَيْتَهُ", ar: "سَبَّبْتَ لَهُ الأَذَى وَالْأَلَمَ", id: "Kamu menyakitinya", en: "You harmed it" }
                ],
                kuis: [
                    { type: "mcq", id: "k2-2-q1", question: "أَيْنَ كَانَ الْوَلَدُ الْفَقِيرُ جَالِسًا؟", options: ["فِي الْبَيْتِ", "فِي الطَّرِيقِ", "فِي الْمَدْرَسَةِ", "فِي الحَدِيقَةِ"], answer: 1 },
                    { type: "mcq", id: "k2-2-q2", question: "مَاذَا رَمَى الْوَلَدُ عَلَى الْكَلْبِ؟", options: ["خُبْزًا", "مَاءً", "حَجَرًا", "عَصَا"], answer: 2 },
                    { type: "mcq", id: "k2-2-q3", question: "مَاذَا فَعَلَ الْكَلْبُ بَعْدَ أَنْ رَمَاهُ الْوَلَدُ؟", options: ["هَرَبَ", "نَامَ", "نَبَحَ وَعَضَّهُ", "لَعِبَ مَعَهُ"], answer: 2 },
                    { type: "mcq", id: "k2-2-q4", question: "مَنْ قَالَ لِلْوَلَدِ «الشَّرُّ بِالشَّرِّ»؟", options: ["أَبُوهُ", "أُمُّهُ", "صَدِيقُهُ", "شَيْخٌ"], answer: 3 },
                    { type: "mcq", id: "k2-2-q5", question: "مَا الدَّرْسُ الْمُسْتَفَادُ مِنْ هَذِهِ الْقِصَّةِ؟", options: ["يَجِبُ إِطْعَامُ الحَيَوَانَاتِ", "مَنْ يُؤْذِ غَيْرَهُ سَيَنَالُ الأَذَى", "الكِلَابُ خَطِيرَةٌ دَائِمًا", "الأَوْلَادُ الفُقَرَاءُ شِرِّيرُون"], answer: 1 },
                    { type: "essay", id: "k2-2-q6", question: "هَلْ تَعْتَقِدُ أَنَّ الوَلَدَ تَعَلَّمَ دَرْسًا مُهِمًّا؟ لِمَاذَا؟ اُكْتُبْ بِاللُّغَةِ الْعَرَبِيَّةِ أَوِ الْإِنْدُوْنِيسِيَّةِ.", keywords: ["درس", "أذى", "تعلم", "pelajaran", "belajar", "menyakiti", "baik"] },
                    { type: "mufradat", id: "k2-2-q7", question: "مَا مَعْنَى «عَضَّهُ» فِي هَذِهِ الْقِصَّةِ؟", options: ["Memukulnya", "Menggigitnya", "Mencakarnya", "Menjualnya"], answer: 1 },
                    { type: "mufradat", id: "k2-2-q8", question: "كَلِمَةُ «حَجَرًا» تَعْنِي بِالْإِنْدُوْنِيسِيَّةِ:", options: ["Ranting pohon", "Sebuah batu", "Sebongkah tanah", "Sepotong kayu"], answer: 1 },
                    { type: "mufradat", id: "k2-2-q9", question: "«آذَيْتَهُ» فِي الْقِصَّةِ تَعْنِي:", options: ["Kamu membantunya", "Kamu melihatnya", "Kamu menyakitinya", "Kamu meninggalkannya"], answer: 2 }
                ]
            },
            {
                id: "k2-3",
                title: "الأَسَدُ وَالْفَأْرُ",
                titleTrans: { id: "Singa dan Tikus", en: "The Lion and the Mouse" },
                text: `كَانَ أَسَدٌ نَائِمًا فَأَتَى فَأْرٌ وَمَشَى عَلَى رَأْسِهِ. فَهَبَّ مِنَ النَّوْمِ غَضْبَانَ وَأَمْسَكَ الْفَأْرَ بِمَخَالِبِهِ. فَقَالَ الْفَأْرُ : اعْفُ عَنِّي يَا سَيِّدِي وَسَأُكَافِئُكَ يَوْمًا مَا. فَأَطْلَقَ الأَسَدُ سَرَاحَهُ ضَاحِكًا. وَبَعْدَ أَيَّامٍ وَقَعَ الأَسَدُ فِي شَبَكَةِ الصَّيَّادِ فَلَمْ يَسْتَطِعِ الْخُرُوجَ. فَسَمِعَ الْفَأْرُ صَوْتَ أَنِينِهِ فَجَاءَ وَقَطَعَ الشَّبَكَةَ بِأَسْنَانِهِ فَأَنْقَذَهُ.`,
                translation: `Seekor singa sedang tidur, lalu datanglah seekor tikus berjalan di atas kepalanya. Singa terbangun dalam keadaan marah dan menangkap tikus itu dengan cakarnya. Tikus berkata: Maafkan aku, tuanku, aku akan membalasmu suatu hari. Singa pun melepaskannya sambil tertawa. Beberapa hari kemudian, singa terjatuh ke dalam jaring pemburu dan tidak bisa keluar. Tikus mendengar rintihan singa, lalu datang dan memotong jaring itu dengan giginya sehingga singa selamat.`,
                kosakataPenting: [
                    { kata: "مَخَالِبِهِ", ar: "جَمْعُ مِخْلَبٍ: أَظَافِرُ الأَسَدِ وَنَحْوِهِ", id: "Cakar-cakarnya", en: "Its claws" },
                    { kata: "سَرَاحَهُ", ar: "أَطْلَقَهُ حُرًّا، أَعَادَ لَهُ حُرِّيَّتَهُ", id: "Kebebasannya", en: "His freedom" },
                    { kata: "شَبَكَةِ", ar: "أَدَاةُ الصَّيْدِ الْمَنْسُوجَةُ مِنَ الخُيُوط", id: "Jaring", en: "Net" },
                    { kata: "أَنِينِهِ", ar: "الصَّوْتُ الَّذِي يَصْدُرُ عَنِ المُتَأَلِّمِ", id: "Raungan sakitnya / Rintihanya", en: "His moaning" },
                    { kata: "فَأَنْقَذَهُ", ar: "خَلَّصَهُ وَنَجَّاهُ مِنَ الأَسْرِ", id: "Lalu menyelamatkannya", en: "Then saved him" }
                ],
                kuis: [
                    { type: "mcq", id: "k2-3-q1", question: "مَاذَا كَانَ يَفْعَلُ الأَسَدُ حِيْنَ جَاءَ الْفَأْرُ؟", options: ["كَانَ يَأْكُلُ", "كَانَ يَلْعَبُ", "كَانَ نَائِمًا", "كَانَ يَصِيدُ"], answer: 2 },
                    { type: "mcq", id: "k2-3-q2", question: "بِمَ أَمْسَكَ الأَسَدُ الْفَأْرَ؟", options: ["بِيَدِهِ", "بِمَخَالِبِهِ", "بِفَمِهِ", "بِشَبَكَةٍ"], answer: 1 },
                    { type: "mcq", id: "k2-3-q3", question: "كَيْفَ أَنْقَذَ الْفَأْرُ الأَسَدَ مِنَ الشَّبَكَةِ؟", options: ["طَلَبَ المُسَاعَدَةَ مِنَ الصَّيَّادِ", "قَطَعَ الشَّبَكَةَ بِأَسْنَانِهِ", "حَمَلَ الأَسَدَ بَعِيدًا", "أَخَافَ الصَّيَّادَ"], answer: 1 },
                    { type: "mcq", id: "k2-3-q4", question: "لِمَاذَا أَطْلَقَ الأَسَدُ سَرَاحَ الْفَأْرِ فِي الْبِدَايَةِ؟", options: ["لِأَنَّهُ كَانَ خَائِفًا", "لِأَنَّ الْفَأْرَ وَعَدَهُ بِالمُكَافَأَةِ وَضَحِكَ مِنْهُ", "لِأَنَّهُ كَانَ جَائِعًا", "لِأَنَّ الفَأْرَ صَدِيقُهُ"], answer: 1 },
                    { type: "mcq", id: "k2-3-q5", question: "مَا الدَّرْسُ الرَّئِيسِيُّ مِنْ هَذِهِ الْقِصَّةِ؟", options: ["الأَسَدُ أَقْوَى مِنَ الفَأْر", "لَا تَحْتَقِرِ الضَّعِيفَ فَقَدْ يُنْقِذُكَ", "الفَأْرُ خَطِيرٌ جِدًّا", "يَجِبُ النَّوْمُ بَعِيدًا عَنِ الحَيَوَانَات"], answer: 1 },
                    { type: "essay", id: "k2-3-q6", question: "اُذْكُرْ صِفَتَيْنِ مِنْ صِفَاتِ الفَأْرِ الْحَسَنَةِ الَّتِي ظَهَرَتْ فِي هَذِهِ الْقِصَّةِ.", keywords: ["وفاء", "شجاع", "صادق", "وعد", "وفى", "membantu", "menepati", "berani", "janji"] },
                    { type: "mufradat", id: "k2-3-q7", question: "مَا مَعْنَى «مَخَالِبِهِ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Giginya", "Ekornya", "Cakar-cakarnya", "Kukunya"], answer: 2 },
                    { type: "mufradat", id: "k2-3-q8", question: "«شَبَكَةِ» فِي هَذِهِ الْقِصَّةِ تَعْنِي:", options: ["Kandang", "Jaring", "Sumur", "Jurang"], answer: 1 },
                    { type: "mufradat", id: "k2-3-q9", question: "اخْتَرِ الْمَعْنَى الصَّحِيحَ لِكَلِمَةِ «فَأَنْقَذَهُ»:", options: ["Lalu menangkapnya", "Lalu melupakannya", "Lalu menyelamatkannya", "Lalu meninggalkannya"], answer: 2 }
                ]
            },
            {
                id: "k2-4",
                title: "الثَّعْلَبُ وَالْعَنْزُ",
                titleTrans: { id: "Rubah dan Kambing", en: "The Fox and the Goat" },
                text: `عَطِشَ ثَعْلَبٌ. وَذَهَبَ إِلَى بِئْرٍ لِيَشْرَبَ فَسَقَطَ فِيهَا. وَلَمَّا شَرِبَ أَرَادَ الْخُرُوجَ فَلَمْ يَقْدِرْ. فَجَاءَتْ عَنْزٌ وَأَشْرَفَتْ عَلَى الْبِئْرِ. فَقَالَ لَهَا الثَّعْلَبُ : اِنْزِلِي فَإِنَّ الْمَاءَ بَارِدٌ وَعَذْبٌ. فَنَزَلَتِ الْعَنْزُ وَشَرِبَتْ. فَطَلَبَ الثَّعْلَبُ مِنْهَا أَنْ تَثْبُتَ وَيَقِفَ هُوَ عَلَى ظَهْرِهَا لِيَخْرُجَ. فَأَذِنَتْ لَهُ. فَخَرَجَ الثَّعْلَبُ وَتَرَكَ الْعَنْزَ فِي الْبِئْرِ.`,
                translation: `Seekor rubah kehausan. Ia pergi ke sebuah sumur untuk minum lalu terjatuh ke dalamnya. Setelah minum, ia ingin keluar namun tidak bisa. Datanglah seekor kambing dan mengintip ke dalam sumur. Rubah berkata kepadanya: Turunlah! Airnya sejuk dan segar. Kambing pun turun dan minum. Rubah meminta kambing agar berdiam diri dan ia berdiri di atas punggungnya untuk keluar. Kambing mengizinkannya. Rubah pun keluar dan meninggalkan kambing di dalam sumur.`,
                kosakataPenting: [
                    { kata: "بِئْرٍ", ar: "حُفْرَةٌ عَمِيقَةٌ فِي الأَرْضِ يُسْتَخْرَجُ مِنْهَا الْمَاء", id: "Sumur", en: "A well" },
                    { kata: "عَذْبٌ", ar: "طَيِّبُ الطَّعْمِ، ضِدُّ الْمِلْح", id: "Tawar / Segar", en: "Fresh / Sweet" },
                    { kata: "أَشْرَفَتْ", ar: "نَظَرَتْ مِنْ فَوْقٍ إِلَى أَسْفَل", id: "Mengintip / Memandang dari atas", en: "She peered over" },
                    { kata: "تَثْبُتَ", ar: "تَقِفَ وَلَا تَتَحَرَّكَ", id: "Tetap diam / Tidak bergerak", en: "To stay still" }
                ],
                kuis: [
                    { type: "mcq", id: "k2-4-q1", question: "لِمَاذَا ذَهَبَ الثَّعْلَبُ إِلَى الْبِئْرِ؟", options: ["لِيَسْبَحَ", "لِيَشْرَبَ لِأَنَّهُ عَطِشَ", "لِيَصِيدَ السَّمَكَ", "لِيَنَامَ"], answer: 1 },
                    { type: "mcq", id: "k2-4-q2", question: "بِمَاذَا وَصَفَ الثَّعْلَبُ الْمَاءَ لِلْعَنْزِ؟", options: ["مَالِحٌ وَدَافِئٌ", "بَارِدٌ وَعَذْبٌ", "قَدِيمٌ وَغَيْرُ نَظِيفٍ", "قَلِيلٌ"], answer: 1 },
                    { type: "mcq", id: "k2-4-q3", question: "كَيْفَ خَرَجَ الثَّعْلَبُ مِنَ الْبِئْرِ؟", options: ["بِمُسَاعَدَةِ الصَّيَّاد", "قَفَزَ وَحْدَهُ", "وَقَفَ عَلَى ظَهْرِ الْعَنْزِ", "رَبَطَ حَبْلًا"], answer: 2 },
                    { type: "mcq", id: "k2-4-q4", question: "مَاذَا فَعَلَ الثَّعْلَبُ بَعْدَ خُرُوجِهِ مِنَ الْبِئْرِ؟", options: ["أَعَانَ الْعَنْزَ عَلَى الخُرُوج", "شَكَرَ الْعَنْزَ", "تَرَكَ الْعَنْزَ فِي الْبِئْر", "اسْتَدْعَى المُزَارِعَ"], answer: 2 },
                    { type: "mcq", id: "k2-4-q5", question: "مَا صِفَةُ الثَّعْلَبِ فِي هَذِهِ الْقِصَّةِ؟", options: ["كَرِيمٌ وَوَفِيٌّ", "مَاكِرٌ وَغَادِرٌ", "شُجَاعٌ وَأَمِينٌ", "خَائِفٌ وَضَعِيفٌ"], answer: 1 },
                    { type: "essay", id: "k2-4-q6", question: "مَا الدَّرْسُ الَّذِي تَعَلَّمْتَهُ مِنْ تَصَرُّفِ الثَّعْلَبِ مَعَ الْعَنْزِ؟", keywords: ["غش", "خداع", "مكر", "خيانة", "tipu", "khianat", "curang", "amanah"] },
                    { type: "mufradat", id: "k2-4-q7", question: "مَا مَعْنَى «بِئْرٍ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Sungai", "Danau", "Sumur", "Laut"], answer: 2 },
                    { type: "mufradat", id: "k2-4-q8", question: "«عَذْبٌ» فِي وَصْفِ الْمَاءِ تَعْنِي:", options: ["Asin", "Panas", "Keruh", "Segar / Tawar"], answer: 3 },
                    { type: "mufradat", id: "k2-4-q9", question: "مَعْنَى «أَشْرَفَتْ» فِي الْقِصَّةِ هُوَ:", options: ["Turun ke bawah", "Mengintip / Memandang dari atas", "Berlari dengan cepat", "Minum dengan lahap"], answer: 1 }
                ]
            },
            {
                id: "k2-5",
                title: "الصَّبِيُّ وَالْفِيلُ",
                titleTrans: { id: "Anak Kecil dan Gajah", en: "The Boy and the Elephant" },
                text: `كَانَ وَلَدٌ يَنْظُرُ الْفِيلَ فِي جَنِينَةِ الحَيَوَانَاتِ. فَمَدَّ يَدَهُ إِلَيْهِ بِتُفَّاحَةٍ. فَأَخَذَ الْفِيلُ التُّفَّاحَةَ بِخُرْطُومِهِ وَرَمَاهَا بَعِيدًا. فَبَكَى الْوَلَدُ. فَجَاءَتِ الحَارِسَةُ وَسَأَلَتْهُ. فَقَالَ لَهَا : أَعْطَيْتُهُ تُفَّاحَةً فَرَمَاهَا. فَقَالَتْ : وَلِمَاذَا تَعْجَبُ؟ هُوَ لَا يُحِبُّ التُّفَّاحَ.`,
                translation: `Seorang anak sedang melihat gajah di kebun binatang. Ia mengulurkan tangannya memberikan sebuah apel. Gajah mengambil apel itu dengan belalainya lalu melemparkannya jauh-jauh. Anak itu pun menangis. Datanglah penjaga wanita dan menanyainya. Ia berkata: Aku memberikan apel kepadanya tapi ia melemparkannya. Penjaga berkata: Mengapa kamu heran? Ia memang tidak suka apel.`,
                kosakataPenting: [
                    { kata: "جَنِينَةِ", ar: "حَدِيقَةٌ فِيهَا حَيَوَانَات يَتَفَرَّجُ عَلَيْهَا النَّاس", id: "Kebun / Taman (Binatang)", en: "Garden / Zoo" },
                    { kata: "خُرْطُومِهِ", ar: "الأَنْفُ الطَّوِيلُ الخَاصُّ بِالفِيل", id: "Belalainya", en: "Its trunk" },
                    { kata: "الحَارِسَةُ", ar: "المَرْأَةُ الَّتِي تَحْرُسُ الْمَكَان", id: "Penjaga wanita", en: "The female guard" }
                ],
                kuis: [
                    { type: "mcq", id: "k2-5-q1", question: "أَيْنَ كَانَ الوَلَدُ حِيْنَ رَأَى الْفِيلَ؟", options: ["فِي الشَّارِعِ", "فِي جَنِينَةِ الحَيَوَانَاتِ", "فِي الغَابَةِ", "فِي المَزْرَعَةِ"], answer: 1 },
                    { type: "mcq", id: "k2-5-q2", question: "مَاذَا أَعْطَى الوَلَدُ لِلْفِيلِ؟", options: ["مَوْزًا", "خُبْزًا", "تُفَّاحَةً", "مَاءً"], answer: 2 },
                    { type: "mcq", id: "k2-5-q3", question: "بِمَ أَخَذَ الفِيلُ التُّفَّاحَةَ؟", options: ["بِيَدِهِ", "بِفَمِهِ", "بِخُرْطُومِهِ", "بِقَدَمِهِ"], answer: 2 },
                    { type: "mcq", id: "k2-5-q4", question: "لِمَاذَا رَمَى الفِيلُ التُّفَّاحَةَ بَعِيدًا؟", options: ["لِأَنَّهُ غَاضِبٌ", "لِأَنَّهُ لَا يُحِبُّ التُّفَّاح", "لِأَنَّهُ شَبْعَانُ", "لِأَنَّ التُّفَّاحَةَ فَاسِدَةٌ"], answer: 1 },
                    { type: "mcq", id: "k2-5-q5", question: "مَا الدَّرْسُ مِنْ هَذِهِ الْقِصَّةِ؟", options: ["الفِيلُ حَيَوَانٌ عَدَوَانِيٌّ", "يَجِبُ أَنْ نَعْرِفَ مَا يُحِبُّهُ الآخَرُون", "لَا تَزُرِ الحَدِيقَةَ وَحْدَكَ", "التُّفَّاحُ غَيْرُ مُفِيد"], answer: 1 },
                    { type: "essay", id: "k2-5-q6", question: "مَا رَأْيُكَ؟ هَلِ الوَلَدُ مُخْطِئٌ أَمِ الفِيلُ؟ وَلِمَاذَا؟", keywords: ["نية", "جيدة", "طيبة", "لا يعرف", "نiat", "baik", "tidak tahu", "salah", "benar"] },
                    { type: "mufradat", id: "k2-5-q7", question: "مَا مَعْنَى «جَنِينَةِ الحَيَوَانَاتِ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Hutan belantara", "Kebun binatang", "Ladang pertanian", "Kolam renang"], answer: 1 },
                    { type: "mufradat", id: "k2-5-q8", question: "«خُرْطُومِهِ» تَعْنِي بِالْإِنْدُوْنِيسِيَّةِ:", options: ["Giginya", "Telinganya", "Belalainya", "Ekornya"], answer: 2 },
                    { type: "mufradat", id: "k2-5-q9", question: "«الحَارِسَةُ» فِي الْقِصَّةِ تَعْنِي:", options: ["Pelanggan wanita", "Penjaga wanita", "Dokter hewan wanita", "Pengunjung wanita"], answer: 1 }
                ]
            }
        ],
        kelas3: [
            {
                id: "k3-1",
                title: "الأَدَبُ أَسَاسُ النَّجَاحِ",
                titleTrans: { id: "Adab adalah Kunci Kesuksesan", en: "Etiquette is the Foundation of Success" },
                text: `أَعْلَنَ تَاجِرٌ أَنَّهُ يُرِيدُ أَنْ يَسْتَخْدِمَ عِنْدَهُ شَابًّا كَاتِبًا. فَقَدَّمَ مِائَةُ شَابٍّ أَنْفُسَهُمْ لِلْعَمَلِ. فَلَمَّا دَخَلَ أَوَّلُهُمْ، دَهَسَ وَرَقَةً كَانَتْ عَلَى الْأَرْضِ بِقَدَمِهِ ثُمَّ جَلَسَ. فَسَأَلَهُ التَّاجِرُ : هَلِ اسْتَعْدَدْتَ لِهَذَا الْعَمَلِ؟ فَأَجَابَ : نَعَمْ. وَكَذَلِكَ سَائِرُ الشُّبَّانِ. وَلَكِنَّ آخِرَهُمْ حِيْنَ دَخَلَ رَأَى الْوَرَقَةَ فَرَفَعَهَا وَوَضَعَهَا عَلَى الطَّاوِلَةِ ثُمَّ جَلَسَ. فَاخْتَارَهُ التَّاجِرُ لِلْعَمَلِ. فَتَعَجَّبَ الآخَرُونَ. فَقَالَ التَّاجِرُ : الأَدَبُ أَسَاسُ النَّجَاحِ.`,
                translation: `Seorang pedagang mengumumkan bahwa ia ingin mempekerjakan seorang pemuda sebagai penulis. Seratus pemuda pun mengajukan diri untuk bekerja. Ketika pemuda pertama masuk, ia menginjak selembar kertas yang ada di lantai dengan kakinya lalu duduk. Pedagang bertanya: Apakah kamu sudah siap untuk pekerjaan ini? Ia menjawab: Ya. Demikian pula dengan pemuda-pemuda yang lainnya. Namun pemuda terakhir, ketika masuk, ia melihat kertas itu lalu memungutnya dan meletakkannya di atas meja, baru kemudian duduk. Pedagang pun memilihnya untuk bekerja. Pemuda-pemuda lain pun heran. Pedagang berkata: Adab adalah fondasi kesuksesan.`,
                kosakataPenting: [
                    { kata: "أَعْلَنَ", ar: "أَخْبَرَ النَّاسَ عَلَنًا بِخَبَرٍ مَا", id: "Mengumumkan", en: "Announced" },
                    { kata: "دَهَسَ", ar: "وَطِئَ بِقَدَمِهِ عَلَى شَيْءٍ", id: "Menginjak", en: "He trampled / stepped on" },
                    { kata: "اسْتَعْدَدْتَ", ar: "أَعْدَدْتَ نَفْسَكَ وَتَهَيَّأْتَ لِشَيْءٍ", id: "Kamu sudah mempersiapkan diri", en: "You prepared yourself" },
                    { kata: "سَائِرُ", ar: "بَقِيَّةُ الشَّيْءِ، جَمِيعُهُم", id: "Seluruh / Semua yang lain", en: "All the rest" },
                    { kata: "فَتَعَجَّبَ", ar: "شَعَرَ بِالدَّهْشَةِ وَالاسْتِغْرَاب", id: "Mereka pun heran / terkejut", en: "They were amazed" }
                ],
                kuis: [
                    { type: "mcq", id: "k3-1-q1", question: "كَمْ شَابًّا تَقَدَّمَ لِلْعَمَلِ عِنْدَ التَّاجِرِ؟", options: ["عَشَرَةٌ", "خَمْسُونَ", "مِائَةٌ", "أَلْفٌ"], answer: 2 },
                    { type: "mcq", id: "k3-1-q2", question: "مَاذَا فَعَلَ أَوَّلُ شَابٍّ دَخَلَ عِنْدَ التَّاجِر؟", options: ["رَفَعَ الوَرَقَةَ وَوَضَعَهَا", "دَهَسَ الوَرَقَةَ بِقَدَمِهِ", "أَخَذَ الوَرَقَةَ وَمَزَّقَهَا", "لَمْ يَرَ الوَرَقَةَ"], answer: 1 },
                    { type: "mcq", id: "k3-1-q3", question: "مَاذَا فَعَلَ الشَّابُّ الأَخِيرُ حِيْنَ رَأَى الوَرَقَةَ؟", options: ["دَهَسَهَا مِثْلَ الآخَرِين", "جَلَسَ عَلَيْهَا", "رَفَعَهَا وَوَضَعَهَا عَلَى الطَّاوِلَة", "لَمْ يَكْتَرِثْ بِهَا"], answer: 2 },
                    { type: "mcq", id: "k3-1-q4", question: "لِمَاذَا اخْتَارَ التَّاجِرُ الشَّابَّ الأَخِيرَ؟", options: ["لِأَنَّهُ الأَجْمَلُ", "لِأَنَّهُ أَذْكَى المُتَقَدِّمِين", "لِأَنَّهُ أَظْهَرَ الأَدَبَ وَالاهْتِمَامَ", "لِأَنَّهُ الأَوَّلُ في الدُّخُول"], answer: 2 },
                    { type: "mcq", id: "k3-1-q5", question: "مَا مَعْنَى مَقُولَةِ «الأَدَبُ أَسَاسُ النَّجَاح»؟", options: ["النَّجَاحُ يَأْتِي بِالمَال", "حُسْنُ الخُلُقِ ضَرُورِيٌّ لِلنَّجَاح", "الذَّكَاءُ أَهَمُّ شَيْء", "يَجِبُ جَمْعُ الوَرَق"], answer: 1 },
                    { type: "essay", id: "k3-1-q6", question: "كَيْفَ يُمْكِنُكَ تَطْبِيقَ مَبْدَأِ «الأَدَبُ أَسَاسُ النَّجَاح» فِي حَيَاتِكَ الْيَوْمِيَّةِ؟", keywords: ["أدب", "اهتمام", "نظافة", "احترام", "sopan", "hormat", "bersih", "peduli"] },
                    { type: "mufradat", id: "k3-1-q7", question: "مَا مَعْنَى «دَهَسَ» فِي هَذِهِ الْقِصَّةِ؟", options: ["Mengangkat", "Menginjak", "Menyapu", "Melempar"], answer: 1 },
                    { type: "mufradat", id: "k3-1-q8", question: "«سَائِرُ الشُّبَّانِ» يَعْنِي:", options: ["Sebagian pemuda saja", "Satu pemuda pilihan", "Seluruh / Semua pemuda yang lain", "Pemuda paling pintar"], answer: 2 },
                    { type: "mufradat", id: "k3-1-q9", question: "«فَتَعَجَّبَ» تَعْنِي:", options: ["Mereka pun marah", "Mereka pun heran / terkejut", "Mereka pun senang", "Mereka pun pergi"], answer: 1 }
                ]
            },
            {
                id: "k3-2",
                title: "الفَلَّاحُ وَاللِّفْتُ",
                titleTrans: { id: "Petani dan Lobak", en: "The Farmer and the Turnip" },
                text: `كَانَ لِفَلَّاحٍ فَقِيرٍ حَقْلٌ صَغِيرٌ يَزْرَعُ فِيهِ اللِّفْتَ. وَكَانَ يَعْمَلُ فِيهِ كُلَّ يَوْمٍ بِجِدٍّ. وَفِي يَوْمٍ نَبَتَتْ لِفْتَةٌ كَبِيرَةٌ جِدًّا. فَشَدَّهَا الْفَلَّاحُ فَلَمْ تَنْقَلِعْ. فَاسْتَعَانَ بِزَوْجَتِهِ فَلَمْ تَنْقَلِعْ. فَأَضَافُوا الوَلَدَ فَلَمْ تَنْقَلِعْ. وَالبِنْتَ فَلَمْ تَنْقَلِعْ. وَالكَلْبَ وَالقِطَّةَ وَالفَأْرَ. فَلَمَّا جَاءَ الفَأْرُ وَشَدَّ مَعَهُمُ انْقَلَعَتِ اللِّفْتَةُ. وَفَرِحُوا جَمِيعًا.`,
                translation: `Seorang petani miskin memiliki ladang kecil tempat ia menanam lobak. Ia bekerja di sana setiap hari dengan tekun. Suatu hari tumbuhlah sebuah lobak yang sangat besar. Petani menariknya namun tidak tercabut. Ia meminta bantuan istrinya namun tidak tercabut. Ditambah anaknya namun tidak tercabut. Dan anak perempuannya pun tidak berhasil. Begitu pula anjing, kucing, dan tikus. Ketika tikus datang dan ikut menarik bersama mereka, lobak itu pun tercabut. Dan mereka semua pun bersukacita.`,
                kosakataPenting: [
                    { kata: "اللِّفْتَ", ar: "نَبَاتٌ مِنَ الفَصِيلَةِ الصَّلِيبِيَّة، جُذُورُهُ تُؤْكَل", id: "Lobak (sejenis sayuran umbi)", en: "Turnip" },
                    { kata: "بِجِدٍّ", ar: "بِاجْتِهَادٍ وَعَزِيمَةٍ بِدُونِ كَسَل", id: "Dengan sungguh-sungguh", en: "Diligently / Earnestly" },
                    { kata: "تَنْقَلِعْ", ar: "تَنْتَزِعُ مِنَ الأَرْضِ وَتَخْرُجُ مِنْهَا", id: "Tercabut", en: "To be uprooted" },
                    { kata: "اسْتَعَانَ", ar: "طَلَبَ الْعَوْنَ وَالمُسَاعَدَةَ مِنْ غَيْرِهِ", id: "Meminta bantuan", en: "Sought help" }
                ],
                kuis: [
                    { type: "mcq", id: "k3-2-q1", question: "مَاذَا كَانَ الفَلَّاحُ يَزْرَعُ فِي حَقْلِهِ؟", options: ["القَمْح", "اللِّفْت", "البَصَل", "الذُّرَة"], answer: 1 },
                    { type: "mcq", id: "k3-2-q2", question: "مَا الَّذِي أَدْهَشَ الفَلَّاحَ فِي ذَلِكَ الْيَوْمِ؟", options: ["مَطَرٌ غَزِيرٌ", "ظُهُورُ حَيَوَانٍ غَرِيبٍ", "نَبَاتُ لِفْتَةٍ كَبِيرَةٍ جِدًّا", "زَوْجَتُهُ أَتَتْ بِطَعَامٍ"], answer: 2 },
                    { type: "mcq", id: "k3-2-q3", question: "مَنْ كَانَ آخِرَ مَنِ انْضَمَّ لِلْمُسَاعَدَةِ؟", options: ["الزَّوْجَةُ", "الكَلْبُ", "الفَأْرُ", "الوَلَدُ"], answer: 2 },
                    { type: "mcq", id: "k3-2-q4", question: "مَتَى انْقَلَعَتِ اللِّفْتَةُ؟", options: ["حِيْنَ شَدَّهَا الفَلَّاحُ وَحْدَهُ", "حِيْنَ جَاءَ الفَأْرُ وَشَدَّ مَعَهُم", "حِيْنَ جَاءَتِ الزَّوْجَةُ", "حِيْنَ جَاءَ الكَلْبُ"], answer: 1 },
                    { type: "mcq", id: "k3-2-q5", question: "مَا الدَّرْسُ الرَّئِيسِيُّ مِنْ قِصَّةِ الفَلَّاحِ وَاللِّفْت؟", options: ["اللِّفْتُ غِذَاءٌ مُهِمّ", "لَا تَعْمَلْ فِي الزِّرَاعَة", "التَّعَاوُنُ يَتَغَلَّبُ عَلَى الصُّعُوبَات", "الفَأْرُ أَقْوَى مِنَ الكَلْب"], answer: 2 },
                    { type: "essay", id: "k3-2-q6", question: "لَوْ لَمْ يَأْتِ الفَأْرُ لِلمُسَاعَدَةِ، مَاذَا كَانَ سَيَحْدُثُ؟ وَمَا الدَّرْسُ الَّذِي تَسْتَنْتِجُهُ؟", keywords: ["لم تنقلع", "فشلوا", "تعاون", "مهم", "tidak tercabut", "gagal", "kerjasama", "penting"] },
                    { type: "mufradat", id: "k3-2-q7", question: "مَا مَعْنَى «بِجِدٍّ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Dengan santai", "Dengan penuh kesenangan", "Dengan sungguh-sungguh", "Dengan malas"], answer: 2 },
                    { type: "mufradat", id: "k3-2-q8", question: "«تَنْقَلِعْ» فِي الْقِصَّةِ تَعْنِي:", options: ["Tumbuh", "Tercabut", "Bertambah besar", "Berbuah"], answer: 1 },
                    { type: "mufradat", id: "k3-2-q9", question: "«اسْتَعَانَ» فِي الْقِصَّةِ تَعْنِي:", options: ["Meminta izin", "Meminta bantuan", "Meminta makanan", "Meminta uang"], answer: 1 }
                ]
            },
            {
                id: "k3-3",
                title: "جَزَاءُ الصِّدْقِ",
                titleTrans: { id: "Balasan Kejujuran", en: "The Reward of Honesty" },
                text: `ذَهَبَ فَلَّاحٌ إِلَى جَارٍ لَهُ غَنِيٍّ مُولَعٍ بِالصَّيْدِ وَشَكَا إِلَيْهِ مَا أَصَابَ القَمْحَ مِنَ العَصَافِيرِ. فَأَعْطَاهُ الجَارُ فَخًّا وَقَالَ لَهُ : اصْطَدِ بِهِ الْعَصَافِيرَ. فَفَرِحَ الفَلَّاحُ وَأَخَذَ الفَخَّ وَوَضَعَهُ فِي حَقْلِهِ. وَفِي الصَّبَاحِ وَجَدَ فِيهِ طَائِرًا كَبِيرًا مَعَ عُصْفُورٍ صَغِيرٍ. فَأَخَذَهُمَا إِلَى جَارِهِ فَقَالَ لَهُ : أَيُّهُمَا أُرِيدُ أَنْ آخُذَ؟ فَأَجَابَهُ : خُذِ الطَّائِرَ الكَبِيرَ. فَأَخَذَ الفَلَّاحُ الطَّائِرَ الصَّغِيرَ وَقَالَ : لَا. بَلْ آخُذُ الصَّغِيرَ. فَتَعَجَّبَ الجَارُ. فَقَالَ الفَلَّاحُ : أَنَا وَضَعْتُ الفَخَّ لِأَصِيدَ العَصَافِيرَ لَا الطُّيُورَ الكَبِيرَةَ.`,
                translation: `Seorang petani pergi ke tetangganya yang kaya dan gemar berburu, mengeluhkan kerusakan gandum akibat burung pipit. Tetangga memberikannya perangkap dan berkata: Tangkaplah burung pipit dengan ini. Petani pun senang, mengambil perangkap dan meletakkannya di ladangnya. Di pagi hari, ia menemukan seekor burung besar beserta seekor burung pipit kecil. Ia membawa keduanya ke tetangganya dan berkata: Mana yang boleh aku ambil? Ia menjawab: Ambillah yang besar. Petani mengambil burung yang kecil dan berkata: Tidak, aku ambil yang kecil. Tetangga pun heran. Petani berkata: Aku memasang perangkap untuk menangkap burung pipit, bukan burung besar.`,
                kosakataPenting: [
                    { kata: "مُولَعٍ", ar: "مُغْرَمٌ بِشَيْءٍ، مُحِبٌّ لَهُ كَثِيرًا", id: "Sangat gemar / terobsesi", en: "Obsessed with / Passionate about" },
                    { kata: "العَصَافِيرِ", ar: "جَمْعُ عُصْفُور: طَائِرٌ صَغِيرٌ", id: "Burung-burung pipit", en: "Sparrows" },
                    { kata: "فَخًّا", ar: "أَدَاةٌ لِصَيْدِ الطُّيُورِ وَالحَيَوَانَات", id: "Perangkap / Jebakan", en: "A trap" }
                ],
                kuis: [
                    { type: "mcq", id: "k3-3-q1", question: "مَا الْمُشْكِلَةُ الَّتِي شَكَا مِنْهَا الفَلَّاحُ لِجَارِهِ؟", options: ["نُقْصَانُ الْمَاءِ", "مَرَضُ النَّبَاتِ", "إِتْلَافُ العَصَافِيرِ لِلْقَمْح", "قِلَّةُ الأَمْطَار"], answer: 2 },
                    { type: "mcq", id: "k3-3-q2", question: "مَاذَا وَجَدَ الفَلَّاحُ فِي الفَخِّ صَبَاحًا؟", options: ["عُصْفُورَيْنِ صَغِيرَيْن", "طَائِرًا كَبِيرًا فَقَط", "طَائِرًا كَبِيرًا مَعَ عُصْفُورٍ صَغِير", "لَا شَيْء"], answer: 2 },
                    { type: "mcq", id: "k3-3-q3", question: "أَيَّ الطَّيْرَيْنِ اخْتَارَ الفَلَّاحُ؟", options: ["الكَبِيرَ", "الاثْنَيْن", "الصَّغِيرَ", "لَمْ يَخْتَرْ"], answer: 2 },
                    { type: "mcq", id: "k3-3-q4", question: "لِمَاذَا أَخَذَ الفَلَّاحُ الطَّائِرَ الصَّغِيرَ فَقَط؟", options: ["لِأَنَّ الكَبِيرَ مَرِيضٌ", "لِأَنَّهُ وَضَعَ الفَخَّ لِيَصِيدَ العَصَافِيرَ لَا الطُّيُورَ الكَبِيرَة", "لِأَنَّ الكَبِيرَ عَضَّهُ", "لِأَنَّ جَارَهُ أَمَرَهُ"], answer: 1 },
                    { type: "mcq", id: "k3-3-q5", question: "مَا الصِّفَةُ الرَّئِيسِيَّةُ لِلْفَلَّاحِ فِي هَذِهِ الْقِصَّةِ؟", options: ["الجَشَعُ وَالطَّمَعُ", "الصِّدْقُ وَالأَمَانَة", "الكَسَلُ وَالإِهْمَالُ", "الحِيلَةُ وَالمَكْرُ"], answer: 1 },
                    { type: "essay", id: "k3-3-q6", question: "لَوْ كُنْتَ مَكَانَ الفَلَّاحِ، هَلْ كُنْتَ سَتَأْخُذُ الطَّائِرَ الكَبِيرَ أَمِ الصَّغِيرَ؟ عَلِّلْ إِجَابَتَكَ.", keywords: ["أمانة", "صدق", "حق", "amanah", "jujur", "hak", "benar", "seharusnya"] },
                    { type: "mufradat", id: "k3-3-q7", question: "مَا مَعْنَى «مُولَعٍ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Tidak suka sama sekali", "Sangat gemar / terobsesi", "Sedikit tertarik", "Merasa takut"], answer: 1 },
                    { type: "mufradat", id: "k3-3-q8", question: "«فَخًّا» فِي الْقِصَّةِ تَعْنِي:", options: ["Makanan ternak", "Kandang binatang", "Perangkap / Jebakan", "Sangkar burung"], answer: 2 },
                    { type: "mufradat", id: "k3-3-q9", question: "«العَصَافِيرِ» هِيَ جَمْعُ عُصْفُور، وَتَعْنِي:", options: ["Elang-elang", "Burung-burung pipit", "Merpati-merpati", "Ayam-ayam hutan"], answer: 1 }
                ]
            },
            {
                id: "k3-4",
                title: "مَزِيَّةُ التَّصْوِيرِ",
                titleTrans: { id: "Kelebihan Fotografi", en: "The Virtue of Photography" },
                text: `كَانَ مُصَوِّرٌ مُسَافِرًا وَهُوَ يَحْمِلُ مَبْلَغًا كَبِيرًا مِنَ النُّقُودِ فِي كِيسٍ عَلَّقَهُ حَوْلَ عُنُقِهِ. فَبَاتَ فِي خَانٍ وَوَضَعَ النُّقُودَ تَحْتَ وِسَادَتِهِ. فَسَرَقَهَا مِنْهُ لِصٌّ حِيْنَ نَامَ. فَلَمَّا أَصْبَحَ وَلَمْ يَجِدْ نُقُودَهُ ذَهَبَ إِلَى الحَاكِمِ. فَقَالَ لَهُ الحَاكِمُ : هَلْ عِنْدَكَ دَلِيلٌ عَلَى السَّارِق؟ فَأَخْرَجَ الْمُصَوِّرُ صُوْرَةً فِيهَا وَجْهُ اللِّصِّ وَقَالَ : هَذِهِ صُوْرَتُهُ. فَاسْتَطَاعَ الحَاكِمُ أَنْ يُمْسِكَ بِهِ.`,
                translation: `Seorang fotografer sedang bepergian membawa sejumlah besar uang dalam kantong yang dikalungkan di lehernya. Ia menginap di sebuah penginapan dan meletakkan uang itu di bawah bantalnya. Seorang pencuri mencurinya saat ia tidur. Ketika pagi hari ia tidak menemukan uangnya, ia pergi ke hakim. Hakim berkata kepadanya: Apakah kamu punya bukti tentang pencuri itu? Fotografer pun mengeluarkan sebuah foto yang memperlihatkan wajah pencuri dan berkata: Ini fotonya. Hakim pun berhasil menangkapnya.`,
                kosakataPenting: [
                    { kata: "خَانٍ", ar: "نُزُلٌ قَدِيمٌ، مَكَانٌ لِإِقَامَةِ المُسَافِرِين", id: "Penginapan / Hotel kuno", en: "An inn / caravanserai" },
                    { kata: "وِسَادَتِهِ", ar: "مَا يُوضَعُ تَحْتَ الرَّأْسِ عِنْدَ النَّوْم", id: "Bantalnya", en: "His pillow" },
                    { kata: "لِصٌّ", ar: "الشَّخْصُ الَّذِي يَأْخُذُ مَالَ غَيْرِهِ سِرًّا", id: "Pencuri", en: "A thief" },
                    { kata: "دَلِيلٌ", ar: "بُرْهَانٌ يُثْبِتُ صِحَّةَ أَمْرٍ", id: "Bukti", en: "Evidence / Proof" }
                ],
                kuis: [
                    { type: "mcq", id: "k3-4-q1", question: "أَيْنَ وَضَعَ الْمُصَوِّرُ نُقُودَهُ قَبْلَ النَّوْم؟", options: ["فِي كِيسِهِ", "تَحْتَ الفِرَاشِ", "تَحْتَ وِسَادَتِهِ", "فِي الجَيْب"], answer: 2 },
                    { type: "mcq", id: "k3-4-q2", question: "مَنِ الَّذِي سَرَقَ نُقُودَ الْمُصَوِّرِ؟", options: ["صَاحِبُ الخَانِ", "مُسَافِرٌ آخَر", "لِصٌّ", "أَحَدُ الحُرَّاسِ"], answer: 2 },
                    { type: "mcq", id: "k3-4-q3", question: "مَا الدَّلِيلُ الَّذِي قَدَّمَهُ الْمُصَوِّرُ لِلْحَاكِم؟", options: ["شَاهِدٌ رَأَى اللِّصَّ", "صُوْرَةٌ لِوَجْهِ اللِّصّ", "بَصْمَةُ يَدِ اللِّصّ", "اعْتِرَافُ اللِّصّ"], answer: 1 },
                    { type: "mcq", id: "k3-4-q4", question: "مَا الَّذِي مَيَّزَ الْمُصَوِّرَ عَنِ المُسَافِرِينَ الآخَرِين؟", options: ["كَثْرَةُ مَالِهِ", "امْتِلَاكُهُ كَامِيرَا تُوَثِّقُ الأَدِلَّة", "قُوَّتُهُ الجَسَدِيَّة", "مَعْرِفَتُهُ بِالقَانُون"], answer: 1 },
                    { type: "mcq", id: "k3-4-q5", question: "مَا الدَّرْسُ الرَّئِيسِيُّ مِنْ هَذِهِ الْقِصَّةِ؟", options: ["السَّفَرُ خَطِيرٌ", "التَّصْوِيرُ مُجَرَّدُ هِوَايَة", "الْعِلْمُ وَالمَهَارَةُ يَنْفَعَانِ فِي الأَزَمَات", "لَا تَضَعِ النُّقُودَ تَحْتَ الوِسَادَة"], answer: 2 },
                    { type: "essay", id: "k3-4-q6", question: "كَيْفَ أَنْقَذَتْ مِهْنَةُ التَّصْوِيرِ الْمُصَوِّرَ فِي هَذِهِ الْقِصَّةِ؟ اِشْرَحْ بِالتَّفْصِيل.", keywords: ["صورة", "دليل", "اثبت", "foto", "bukti", "membuktikan", "keahlian", "profesi"] },
                    { type: "mufradat", id: "k3-4-q7", question: "مَا مَعْنَى «خَانٍ» فِي هَذِهِ الْقِصَّةِ؟", options: ["Restoran mewah", "Penginapan / Hotel kuno", "Pasar tradisional", "Warung kecil"], answer: 1 },
                    { type: "mufradat", id: "k3-4-q8", question: "«لِصٌّ» فِي الْقِصَّةِ تَعْنِي:", options: ["Hakim", "Pedagang", "Pencuri", "Penjaga"], answer: 2 },
                    { type: "mufradat", id: "k3-4-q9", question: "مَا مَعْنَى «دَلِيلٌ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Saksi mata", "Bukti / Keterangan", "Laporan polisi", "Pengakuan"], answer: 1 }
                ]
            },
            {
                id: "k3-5",
                title: "سَاعَةُ الحَائِطِ وَالْمِزْوَلَةُ",
                titleTrans: { id: "Jam Dinding dan Jam Matahari", en: "The Wall Clock and the Sundial" },
                text: `كَانَ فِي حَدِيقَةِ دَارٍ كَبِيرَةٍ مِزْوَلَةٌ تُبَيِّنُ الْوَقْتَ. وَكَانَ مِنْ ضِمْنِ الْبِنَاءِ بُرْجٌ عَالٍ تَعْلُوهُ سَاعَةٌ كَبِيرَةٌ. فَكَانَتِ الْمِزْوَلَةُ تَفْخَرُ عَلَى السَّاعَةِ وَتَقُولُ لَهَا : أَنَا أَقْدَمُ مِنْكِ وَأَكْثَرُ نَفْعًا. فَلَمَّا جَاءَ اللَّيْلُ أَوِ انَّتَ السَّمَاءُ بِالْغَيُومِ لَمْ تَسْتَطِعِ الْمِزْوَلَةُ أَنْ تَدُلَّ عَلَى الْوَقْتِ. وَأَمَّا السَّاعَةُ فَكَانَتْ تَدُقُّ فِي كُلِّ لَيْلَةٍ وَنَهَارٍ.`,
                translation: `Di taman sebuah rumah besar terdapat jam matahari yang menunjukkan waktu. Dan di antara bangunan itu ada sebuah menara tinggi yang di atasnya terdapat sebuah jam besar. Jam matahari itu bangga kepada jam dinding dan berkata kepadanya: Aku lebih tua darimu dan lebih bermanfaat. Namun ketika malam tiba atau langit tertutup awan, jam matahari tidak bisa menunjukkan waktu. Sementara jam dinding, ia berdetak siang dan malam.`,
                kosakataPenting: [
                    { kata: "مِزْوَلَةٌ", ar: "أَدَاةٌ قَدِيمَةٌ تَعْمَلُ بِظِلِّ الشَّمْسِ لِمَعْرِفَةِ الوَقْت", id: "Jam matahari (sundial)", en: "A sundial" },
                    { kata: "تَفْخَرُ", ar: "تَتَكَبَّرُ وَتُظْهِرُ عَظَمَتَهَا عَلَى غَيْرِهَا", id: "Merasa bangga / sombong", en: "Boasts / Takes pride" },
                    { kata: "بِالْغَيُومِ", ar: "جَمْعُ غَيْم: السَّحَابُ الكَثِيفُ فِي السَّمَاء", id: "Dengan awan-awan", en: "With clouds" },
                    { kata: "تَدُقُّ", ar: "تَضْرِبُ بِدَقَّاتِهَا المُنْتَظِمَة، صَوْتُ السَّاعَة", id: "Berdetak / Berdentang", en: "Ticks / Chimes" }
                ],
                kuis: [
                    { type: "mcq", id: "k3-5-q1", question: "أَيْنَ كَانَتِ الْمِزْوَلَةُ فِي هَذِهِ الْقِصَّةِ؟", options: ["عَلَى البُرْجِ العَالِي", "فِي حَدِيقَةِ الدَّار", "عَلَى الحَائِط", "فِي غُرْفَةِ النَّوْم"], answer: 1 },
                    { type: "mcq", id: "k3-5-q2", question: "بِمَ افْتَخَرَتِ الْمِزْوَلَةُ عَلَى السَّاعَةِ؟", options: ["بِجَمَالِهَا وَلَوْنِهَا", "بِأَنَّهَا أَقْدَمُ وَأَكْثَرُ نَفْعًا", "بِأَنَّهَا أَكْبَرُ حَجْمًا", "بِأَنَّهَا عَلَى البُرْج"], answer: 1 },
                    { type: "mcq", id: "k3-5-q3", question: "مَتَى عَجَزَتِ الْمِزْوَلَةُ عَنْ بَيَانِ الْوَقْت؟", options: ["فِي الصَّبَاح", "حِيْنَ أَتَى اللَّيْلُ أَوِ انَّتَتِ السَّمَاءُ بِالغَيُوم", "عِنْدَمَا كَسَرَتْ", "لَمْ تَعْجَزْ أَبَدًا"], answer: 1 },
                    { type: "mcq", id: "k3-5-q4", question: "مَا مَيْزَةُ السَّاعَةِ الكَبِيرَةِ عَلَى الْمِزْوَلَة؟", options: ["أَنَّهَا أَجْمَلُ", "أَنَّهَا أَغْلَى ثَمَنًا", "أَنَّهَا تَدُقُّ فِي كُلِّ لَيْلَةٍ وَنَهَار", "أَنَّهَا عَلَى بُرْجٍ عَالٍ"], answer: 2 },
                    { type: "mcq", id: "k3-5-q5", question: "مَا الدَّرْسُ الرَّئِيسِيُّ مِنْ هَذِهِ الْقِصَّةِ؟", options: ["السَّاعَاتُ الحَدِيثَةُ أَفْضَلُ مِنَ القَدِيمَة", "لَا تَتَكَبَّرْ عَلَى غَيْرِكَ فَقَدْ يَتَفَوَّقُ عَلَيْك", "الْمِزْوَلَةُ أَدَاةٌ غَيْرُ مُفِيدَة", "يَجِبُ وَضْعُ السَّاعَاتِ عَلَى الأَبْرَاج"], answer: 1 },
                    { type: "essay", id: "k3-5-q6", question: "مَا الفَرْقُ بَيْنَ الْمِزْوَلَةِ وَالسَّاعَةِ مِنْ حَيْثُ الأَهَمِّيَّةُ وَالاسْتِخْدَام؟ وَمَا رَأْيُكَ؟", keywords: ["شمس", "ليل", "ظل", "مستمر", "matahari", "malam", "bayangan", "terus"] },
                    { type: "mufradat", id: "k3-5-q7", question: "مَا مَعْنَى «مِزْوَلَةٌ» بِالْإِنْدُوْنِيسِيَّةِ؟", options: ["Jam dinding", "Jam tangan", "Jam matahari (sundial)", "Jam pasir"], answer: 2 },
                    { type: "mufradat", id: "k3-5-q8", question: "«تَفْخَرُ» فِي الْقِصَّةِ تَعْنِي:", options: ["Merasa sedih", "Merasa malu", "Merasa bangga / sombong", "Merasa takut"], answer: 2 },
                    { type: "mufradat", id: "k3-5-q9", question: "مَعْنَى «تَدُقُّ» فِي وَصْفِ السَّاعَةِ هُوَ:", options: ["Berputar terus-menerus", "Berdetak / Berdentang", "Berhenti tiba-tiba", "Rusak karena panas"], answer: 1 }
                ]
            }
        ]
    },

    // =========================================================================
    // MUFRADAT (FLASHCARDS)
    // =========================================================================
    mufradat: [
        { arab: "أَسَد", indo: "Singa", en: "Lion" },
        { arab: "فَأْر", indo: "Tikus", en: "Mouse" },
        { arab: "ثَعْلَب", indo: "Rubah", en: "Fox" },
        { arab: "فِيل", indo: "Gajah", en: "Elephant" },
        { arab: "فَلَّاح", indo: "Petani", en: "Farmer" },
        { arab: "تَاجِر", indo: "Pedagang", en: "Merchant" },
        { arab: "لِصّ", indo: "Pencuri", en: "Thief" },
        { arab: "دَلِيل", indo: "Bukti", en: "Evidence" },
        { arab: "حَرِيق", indo: "Kebakaran", en: "Fire / Blaze" },
        { arab: "صِدْق", indo: "Kejujuran", en: "Honesty" },
        { arab: "أَدَب", indo: "Etika / Sopan santun", en: "Etiquette / Manners" },
        { arab: "نَجَاح", indo: "Kesuksesan", en: "Success" }
    ],

    // =========================================================================
    // TERJEMAHAN UI (i18n)
    // =========================================================================
    i18n: {
        ar: {
            appTitle: "تَطْبِيقُ تَعَلُّمِ الْقِرَاءَةِ",
            statusLoggedOut: "الحَالَةُ: غَيْرُ مُسَجَّلٍ",
            statusLoggedIn: "الحَالَةُ:",
            btnLogin: "دُخُول",
            navAuth: "١. التَّحَقُّقُ مِنَ الهَوِيَّة",
            navDashboard: "٢. لَوْحَةُ التَّحَكُّم",
            navMateri: "٣. مَوَادُّ القِرَاءَة",
            navBelajar: "٤. دَرْسُ القِرَاءَةِ",
            navMufradat: "٥. تَدْرِيبُ الْمُفْرَدَات",
            navQuiz: "٦. الاخْتِبَارُ التَّقْيِيمِي",
            navSkor: "٧. الدَّرَجَةُ وَالشَّهَادَة",
            btnLogout: "خُرُوج",
            navSectionTitle: "نِظَامُ التَّنَقُّل",
            guestUser: "ضَيْف",
            guestRole: "الرَّجَاءُ تَسْجِيلُ الدُّخُول",
            loginTabLogin: "تَسْجِيلُ الدُّخُول",
            loginTabRegister: "إِنْشَاءُ حِسَاب",
            loginBadge: "دُخُولُ الْمُسْتَخْدِم",
            loginTitle: "بَوَّابَةُ تَعَلُّمِ الْقِرَاءَة",
            loginDesc: "أَدْخِلِ اسْمَ الْمُسْتَخْدِمِ وَكَلِمَةَ الْمُرُورِ لِلدُّخُولِ",
            loginNimLabel: "رَقْمُ الهُوِيَّة / اسْمُ الْمُسْتَخْدِم",
            loginPassLabel: "كَلِمَةُ الْمُرُور",
            loginSubmit: "دُخُولٌ إِلَى النِّظَام",
            regBadge: "تَسْجِيلُ حِسَابٍ جَدِيد",
            regTitle: "إِنْشَاءُ حِسَابِكَ",
            regDesc: "سَجِّلْ نَفْسَكَ لِحِفْظِ سِجَلِّ التَّعَلُّمِ وَالنَّتَائِج",
            regNimLabel: "رَقْمُ الهُوِيَّة (فَرِيد)",
            regNameLabel: "الاسْمُ الكَامِل",
            regPassLabel: "كَلِمَةُ الْمُرُور",
            regRoleLabel: "دَوْرُ الْمُسْتَخْدِم",
            regSubmit: "تَسْجِيلٌ الآن",
            dashWelcome: "أَهْلًا وَسَهْلًا,",
            dashDesc: "اخْتَرْ مَرْحَلَةَ تَعَلُّمِكَ الآن.",
            cardMaterTitle: "مَوَادُّ القِرَاءَة",
            cardMaterDesc: "قِرَاءَةُ الْمُطَالَعَة",
            cardMufrTitle: "تَدْرِيبُ الْمُفْرَدَات",
            cardMufrDesc: "بِطَاقَاتُ الْمُفْرَدَاتِ",
            cardQuizTitle: "الاخْتِبَارُ التَّقْيِيمِي",
            cardQuizDesc: "اخْتَبِرْ فَهْمَكَ",
            btnOpenModule: "افْتَحِ الوِحْدَة",
            btnStartDrill: "ابْدَأِ التَّدْرِيب",
            btnTakeQuiz: "أَدِّ الاخْتِبَار",
            materHeading: "قَائِمَةُ مَوَادِّ الْمُطَالَعَة",
            materDesc: "اخْتَرْ عُنْوَانَ الْقِرَاءَةِ لِلشُّرُوعِ فِي التَّعَلُّم.",
            btnKelas2: "الصَّفُّ الثَّاني",
            btnKelas3: "الصَّفُّ الثَّالِث",
            mufHeading: "تَدْرِيبُ الْمُفْرَدَاتِ (الكَلِمَات)",
            mufDesc: "انْقُرْ فَوْقَ البِطَاقَةِ لِقَلْبِهَا وَرُؤْيَةِ تَرْجَمَتِهَا.",
            quizHeading: "الاخْتِبَارُ التَّقْيِيمِيُّ النِّهَائِي",
            quizDesc: "أَكْمِلِ الأَسْئِلَةَ لِاخْتِبَارِ فَهْمِكَ.",
            btnSubmitQuiz: "تَسْلِيمُ الإِجَابَاتِ وَحِسَابُ الدَّرَجَة",
            certTitle: "شَهَادَةُ التَّفَوُّق",
            certGivenTo: "تُمْنَحُ إِلَى:",
            certNim: "الرَّقْمُ:",
            certRole: "الدَّوْر:",
            certFinalScore: "الدَّرَجَةُ النِّهَائِيَّة:",
            evalTitle: "التَّوْصِيَاتُ وَتَقْيِيمُ الأَدَاء",
            evalDefault: "يَرْجَى إِجْرَاءُ الاخْتِبَارِ التَّقْيِيمِيِّ أَوَّلًا لِلْحُصُولِ عَلَى التَّحْلِيلِ الشَّخْصِي.",
            bcAuth: "١. الدُّخُول",
            bcDash: "٢. اللَّوْحَة",
            bcMater: "٣. الْوِحْدَة",
            bcBelajar: "٤. الدَّرْس",
            bcMuf: "٥. الْمُفْرَدَات",
            bcQuiz: "٦. الاخْتِبَار",
            bcSkor: "٧. الدَّرَجَة",
            btnBack: "رُجُوع",
            btnPlayAudio: "اِسْتَمِعْ إِلَى الْقِرَاءَة",
            btnPlaying: "جَارٍ التَّشْغِيل...",
            wordModalTitle: "مَعْنَى الْكَلِمَة",
            wordArLabel: "الْمَعْنَى بِالْعَرَبِيَّة:",
            wordIdLabel: "الْمَعْنَى بِالإِنْدُوْنِيسِيَّة:",
            wordEnLabel: "الْمَعْنَى بِالإِنْجِلِيزِيَّة:",
            wordNoData: "لَمْ يَرِدْ تَفْسِيرٌ لِهَذِهِ الكَلِمَةِ فِي قَامُوسِنَا.",
            btnListen: "اِسْمَعِ الكَلِمَة",
            btnClose: "إِغْلَاق",
            authBrand: "Smart Muthala'ah ID",
            authTagline: "مَنْصَّةُ تَعَلُّمِ اللُّغَةِ الْعَرَبِيَّةِ التَّفَاعُلِيَّة",
            progressLabel: "تَقَدُّمُ التَّعَلُّم",
            navStatistik: "إِحْصَاءُ التَّقَدُّم",
            sectionMenu: "الْقَائِمَةُ الرَّئِيسِيَّة",
            chipMateri: "مَادَّةً مَفْتُوحَة",
            chipQuiz: "اخْتِبَارٌ مُكْتَمِل",
            chipAvg: "الْمُعَدَّل:",
            cardStatTitle: "إِحْصَاءُ التَّقَدُّم",
            cardStatDesc: "تَتَبَّعْ تَقَدُّمَكَ فِي التَّعَلُّم",
            btnViewStat: "عَرْضُ الإِحْصَاء",
            materBadge: "مَكْتَبَةُ الْمَوَادّ",
            mufBadge: "بِطَاقَاتُ الْمُفْرَدَات",
            quizBadge: "تَقْيِيمُ الْفَهْم",
            quizBased: "بِنَاءً عَلَى مَادَّة:",
            quizNoMateri: "اخْتَرْ مَادَّةَ الْقِرَاءَةِ أَوَّلًا، ثُمَّ عُدْ إِلَى الاخْتِبَار.",
            quizNoQuestion: "لَا تُوجَدُ أَسْئِلَةٌ لِهَذِهِ الْمَادَّةِ بَعْد.",
            essayPlaceholder: "اُكْتُبْ إِجَابَتَكَ هُنَا...",
            skorBadge: "نَتِيجَةُ التَّقْيِيم",
            skorHeading: "الدَّرَجَةُ وَالشَّهَادَة",
            skorDesc: "هَذِهِ نَتِيجَةُ اخْتِبَارِكَ التَّقْيِيمِي.",
            scoreLabel: "/ 100",
            breakdownTitle: "تَفْصِيلُ النَّتِيجَة",
            bdMcq: "أَسْئِلَةٌ مُتَعَدِّدَةٌ صَحِيحَة",
            bdEssay: "إِجَابَةُ الْمَقَال",
            bdMuf: "مُفْرَدَاتٌ صَحِيحَة",
            btnNextMateri: "مَوَادٌّ أُخْرَى",
            statBadge: "تَقَدُّمُ التَّعَلُّم",
            statHeading: "إِحْصَاءُ تَقَدُّمِ الطَّالِب",
            statDesc: "تَابَعْ مَسِيرَتَكَ التَّعَلُّمِيَّة.",
            statTabOverview: "مُلَخَّص",
            statTabKategori: "الْفِئَات",
            statTabGrafik: "الرَّسْمُ الْبَيَانِي",
            statTotalMateri: "مَوَادُّ مُدْرَسَة",
            statTotalQuiz: "اخْتِبَارٌ مُنْجَز",
            statAvgScore: "مُعَدَّلُ الدَّرَجَات",
            statTotalMuf: "مُفْرَدَاتٌ مُتَعَلَّمَة",
            statProgress: "التَّقَدُّمُ لِكُلِّ مَادَّة",
            statEmpty: "لَا تُوجَدُ بَيَانَاتٌ بَعْد. أَكْمِلِ اخْتِبَارًا لِرُؤْيَةِ تَقَدُّمِك.",
            catMcq: "فَهْمُ النَّص",
            catMcqLabel: "مُعَدَّلُ الأَسْئِلَةِ الْمُتَعَدِّدَة",
            catEssay: "قُدْرَةُ الْكِتَابَة",
            catEssayLabel: "مُعَدَّلُ أَسْئِلَةِ الْمَقَال",
            catMuf: "مُفْرَدَاتُ الْكَلِمَات",
            catMufLabel: "مُعَدَّلُ أَسْئِلَةِ الْمُفْرَدَات",
            catTotal: "الْمُعَدَّلُ الإِجْمَالِي",
            catTotalLabel: "مُعَدَّلُ جَمِيعِ الاخْتِبَارَات",
            catRekomTitle: "تَوْصِيَاتُ التَّحْسِين",
            grafikTitle: "رَسْمُ الدَّرَجَاتِ لِكُلِّ مَادَّة",
            grafikEmpty: "لَا تُوجَدُ بَيَانَاتٌ لِعَرْضِهَا.",
            trendTitle: "اتِّجَاهُ التَّقَدُّم",
            filterAll: "الكُلّ",
            kosakataTitle: "الْكَلِمَاتُ الْمُهِمَّة",
            readInstruction: "انْقُرْ عَلَى أَيِّ كَلِمَةٍ لِمَعْرِفَةِ مَعْنَاهَا وَسَمَاعِ نُطْقِهَا.",
            fcFlipHint: "انْقُرْ لِلْمَعْنَى",
            bcStat: "٧. الإِحْصَاء",
            alertFillAll: "يَرْجَى تَعْبِئَةُ جَمِيعِ الْحُقُول.",
            alertNimExists: "رَقْمُ الهُوِيَّةِ مُسَجَّلٌ مِنْ قَبْل!",
            alertRegSuccess: "تَمَّ التَّسْجِيلُ بِنَجَاح! يَرْجَى تَسْجِيلُ الدُّخُول.",
            alertLoginFail: "رَقْمُ الهُوِيَّةِ أَوِ الرَّمْزُ غَيْرُ صَحِيح.",
            alertChooseMateri: "يَرْجَى اخْتِيَارُ مَادَّةٍ أَوَّلًا."
        },
        id: {
            appTitle: "Aplikasi Pembelajaran Qira'ah",
            statusLoggedOut: "Status: Belum Login",
            statusLoggedIn: "Status:",
            btnLogin: "Login",
            navAuth: "1. Otentikasi Akun",
            navDashboard: "2. Dashboard Utama",
            navMateri: "3. Modul Materi Qira'ah",
            navBelajar: "4. Belajar Qira'ah & Audio",
            navMufradat: "5. Latihan Mufradat",
            navQuiz: "6. Quiz Evaluasi",
            navSkor: "7. Skor & Sertifikat",
            btnLogout: "Keluar / Logout",
            navSectionTitle: "NAVIGASI ALUR SISTEM",
            guestUser: "Tamu",
            guestRole: "Silakan Login / Daftar",
            loginTabLogin: "Masuk (Login)",
            loginTabRegister: "Daftar Akun",
            loginBadge: "Login Pengguna",
            loginTitle: "Portal Pembelajaran Qira'ah",
            loginDesc: "Masukkan NIM dan Kata Sandi untuk Mengakses Modul Pembelajaran",
            loginNimLabel: "NIM / Username",
            loginPassLabel: "Password",
            loginSubmit: "Masuk Ke Sistem",
            regBadge: "Pendaftaran Akun Baru",
            regTitle: "Buat Akun Anda",
            regDesc: "Daftarkan diri untuk menyimpan rekam jejak dan skor evaluasi",
            regNimLabel: "NIM / Username (Unik)",
            regNameLabel: "Nama Lengkap",
            regPassLabel: "Password",
            regRoleLabel: "Peran User",
            regSubmit: "Daftar Sekarang",
            dashWelcome: "Selamat Datang,",
            dashDesc: "Silakan pilih tahapan pembelajaran Anda hari ini.",
            cardMaterTitle: "Materi Qira'ah",
            cardMaterDesc: "Bacaan Muthalaah MTs",
            cardMufrTitle: "Latihan Mufradat",
            cardMufrDesc: "Flashcard Kosakata Arab",
            cardQuizTitle: "Quiz Evaluasi",
            cardQuizDesc: "Uji Pemahaman & Kosakata",
            btnOpenModule: "Buka Modul",
            btnStartDrill: "Mulai Latihan",
            btnTakeQuiz: "Ikuti Kuis",
            materHeading: "Daftar Materi Muthalaah",
            materDesc: "Pilih salah satu judul qira'ah untuk mulai belajar.",
            btnKelas2: "Kelas 2",
            btnKelas3: "Kelas 3",
            mufHeading: "Latihan Mufradat (Kosakata)",
            mufDesc: "Klik kartu untuk membalik dan melihat terjemahannya.",
            quizHeading: "Quiz Evaluasi Akhir",
            quizDesc: "Selesaikan pertanyaan berikut untuk menguji pemahaman Anda.",
            btnSubmitQuiz: "Kumpulkan & Hitung Skor",
            certTitle: "Sertifikat Kelulusan",
            certGivenTo: "Diberikan kepada:",
            certNim: "NIM:",
            certRole: "Peran:",
            certFinalScore: "Nilai Akhir:",
            evalTitle: "Rekomendasi & Saran Evaluasi",
            evalDefault: "Silakan ikuti Quiz Evaluasi terlebih dahulu untuk mendapatkan analisis personal.",
            bcAuth: "1. Akun",
            bcDash: "2. Dashboard",
            bcMater: "3. Modul",
            bcBelajar: "4. Belajar",
            bcMuf: "5. Latihan",
            bcQuiz: "6. Quiz",
            bcSkor: "7. Skor",
            btnBack: "Kembali",
            btnPlayAudio: "Putar Audio (Read-Along)",
            btnPlaying: "Sedang Memutar...",
            wordModalTitle: "Arti Kosakata",
            wordArLabel: "Arti (Arab / Kamus):",
            wordIdLabel: "Arti (Indonesia):",
            wordEnLabel: "Arti (Inggris):",
            wordNoData: "Kata ini belum ada dalam kamus interaktif kami.",
            btnListen: "Dengar Kata",
            btnClose: "Tutup",
            authBrand: "Smart Muthala'ah ID",
            authTagline: "Platform Pembelajaran Bahasa Arab Interaktif",
            progressLabel: "Kemajuan Belajar",
            navStatistik: "Statistik Kemajuan",
            sectionMenu: "Menu Utama",
            chipMateri: "Materi Dibuka",
            chipQuiz: "Kuis Selesai",
            chipAvg: "Rata-rata:",
            cardStatTitle: "Statistik Kemajuan",
            cardStatDesc: "Pantau perkembangan belajar Anda",
            btnViewStat: "Lihat Statistik",
            materBadge: "Perpustakaan Materi",
            mufBadge: "Kartu Kosakata",
            quizBadge: "Evaluasi Pemahaman",
            quizBased: "Berdasarkan materi:",
            quizNoMateri: "Pilih materi bacaan terlebih dahulu, lalu kembali ke sini untuk mengikuti kuis.",
            quizNoQuestion: "Belum ada soal untuk materi ini.",
            essayPlaceholder: "Tuliskan jawabanmu di sini...",
            skorBadge: "Hasil Evaluasi",
            skorHeading: "Skor & Sertifikat",
            skorDesc: "Berikut hasil evaluasi kuis Anda.",
            scoreLabel: "/ 100",
            breakdownTitle: "Rincian Nilai",
            bdMcq: "Pilihan Ganda Benar",
            bdEssay: "Uraian Terisi",
            bdMuf: "Mufradat Tepat",
            btnNextMateri: "Materi Lain",
            statBadge: "Kemajuan Belajar",
            statHeading: "Statistik Kemajuan Siswa",
            statDesc: "Pantau perkembangan belajar Anda dari waktu ke waktu.",
            statTabOverview: "Ringkasan",
            statTabKategori: "Kategori",
            statTabGrafik: "Grafik",
            statTotalMateri: "Materi Dipelajari",
            statTotalQuiz: "Kuis Diselesaikan",
            statAvgScore: "Rata-rata Nilai",
            statTotalMuf: "Kosakata Dipelajari",
            statProgress: "Progres Per Materi",
            statEmpty: "Belum ada data. Selesaikan kuis untuk melihat progres.",
            catMcq: "Pemahaman Teks",
            catMcqLabel: "Rata-rata pilihan ganda",
            catEssay: "Kemampuan Uraian",
            catEssayLabel: "Rata-rata soal uraian",
            catMuf: "Kosakata Mufradat",
            catMufLabel: "Rata-rata soal mufradat",
            catTotal: "Nilai Keseluruhan",
            catTotalLabel: "Rata-rata semua kuis",
            catRekomTitle: "Rekomendasi Peningkatan",
            grafikTitle: "Grafik Nilai per Materi",
            grafikEmpty: "Belum ada data kuis untuk ditampilkan.",
            trendTitle: "Tren Kemajuan",
            filterAll: "Semua",
            kosakataTitle: "Kosakata Penting",
            readInstruction: "Ketuk kata Arab mana saja untuk melihat arti dan mendengar pelafalannya.",
            fcFlipHint: "Ketuk untuk arti",
            bcStat: "⑦ Statistik",
            alertFillAll: "Harap lengkapi semua data.",
            alertNimExists: "NIM/NIS sudah terdaftar!",
            alertRegSuccess: "Pendaftaran berhasil! Silakan login.",
            alertLoginFail: "NIM atau Password salah. Belum punya akun? Daftar dulu.",
            alertChooseMateri: "Pilih materi terlebih dahulu sebelum submit kuis."
        },
        en: {
            appTitle: "Arabic Reading Learning App",
            statusLoggedOut: "Status: Not Logged In",
            statusLoggedIn: "Status:",
            btnLogin: "Login",
            navAuth: "1. Account Authentication",
            navDashboard: "2. Main Dashboard",
            navMateri: "3. Reading Material Module",
            navBelajar: "4. Reading & Audio Lesson",
            navMufradat: "5. Vocabulary Practice",
            navQuiz: "6. Evaluation Quiz",
            navSkor: "7. Score & Certificate",
            btnLogout: "Sign Out / Logout",
            navSectionTitle: "NAVIGATION FLOW",
            guestUser: "Guest",
            guestRole: "Please Login / Register",
            loginTabLogin: "Sign In (Login)",
            loginTabRegister: "Create Account",
            loginBadge: "User Login",
            loginTitle: "Qira'ah Learning Portal",
            loginDesc: "Enter your ID and Password to access the Learning Modules",
            loginNimLabel: "Student ID / Username",
            loginPassLabel: "Password",
            loginSubmit: "Enter the System",
            regBadge: "New Account Registration",
            regTitle: "Create Your Account",
            regDesc: "Register to save your learning history and evaluation scores",
            regNimLabel: "Student ID / Username (Unique)",
            regNameLabel: "Full Name",
            regPassLabel: "Password",
            regRoleLabel: "User Role",
            regSubmit: "Register Now",
            dashWelcome: "Welcome,",
            dashDesc: "Please choose your learning path for today.",
            cardMaterTitle: "Reading Material",
            cardMaterDesc: "Muthalaah MTs Readings",
            cardMufrTitle: "Vocabulary Practice",
            cardMufrDesc: "Arabic Flashcards",
            cardQuizTitle: "Evaluation Quiz",
            cardQuizDesc: "Test Your Comprehension",
            btnOpenModule: "Open Module",
            btnStartDrill: "Start Drill",
            btnTakeQuiz: "Take Quiz",
            materHeading: "Muthalaah Material List",
            materDesc: "Choose a Qira'ah title to start learning.",
            btnKelas2: "Class 2",
            btnKelas3: "Class 3",
            mufHeading: "Vocabulary Practice (Mufradat)",
            mufDesc: "Click a card to flip it and see the translation.",
            quizHeading: "Final Evaluation Quiz",
            quizDesc: "Complete the following questions to test your understanding.",
            btnSubmitQuiz: "Submit & Calculate Score",
            certTitle: "Certificate of Completion",
            certGivenTo: "Awarded to:",
            certNim: "ID:",
            certRole: "Role:",
            certFinalScore: "Final Score:",
            evalTitle: "Recommendations & Performance Review",
            evalDefault: "Please take the Evaluation Quiz first to receive a personalized analysis.",
            bcAuth: "1. Account",
            bcDash: "2. Dashboard",
            bcMater: "3. Module",
            bcBelajar: "4. Lesson",
            bcMuf: "5. Vocabulary",
            bcQuiz: "6. Quiz",
            bcSkor: "7. Score",
            btnBack: "Back",
            btnPlayAudio: "Play Audio (Read-Along)",
            btnPlaying: "Playing...",
            wordModalTitle: "Word Meaning",
            wordArLabel: "Arabic (Dictionary):",
            wordIdLabel: "Indonesian:",
            wordEnLabel: "English:",
            wordNoData: "This word is not yet in our interactive dictionary.",
            btnListen: "Listen to Word",
            btnClose: "Close",
            authBrand: "Smart Muthala'ah ID",
            authTagline: "Interactive Arabic Learning Platform",
            progressLabel: "Learning Progress",
            navStatistik: "Progress Statistics",
            sectionMenu: "Main Menu",
            chipMateri: "Materials Opened",
            chipQuiz: "Quizzes Done",
            chipAvg: "Average:",
            cardStatTitle: "Progress Statistics",
            cardStatDesc: "Track your learning development",
            btnViewStat: "View Statistics",
            materBadge: "Material Library",
            mufBadge: "Vocabulary Cards",
            quizBadge: "Comprehension Evaluation",
            quizBased: "Based on material:",
            quizNoMateri: "Please select a reading material first, then return here to take the quiz.",
            quizNoQuestion: "No questions available for this material yet.",
            essayPlaceholder: "Write your answer here...",
            skorBadge: "Evaluation Results",
            skorHeading: "Score & Certificate",
            skorDesc: "Here are your quiz evaluation results.",
            scoreLabel: "/ 100",
            breakdownTitle: "Score Breakdown",
            bdMcq: "MCQ Correct",
            bdEssay: "Essay Score",
            bdMuf: "Mufradat Correct",
            btnNextMateri: "Other Materials",
            statBadge: "Learning Progress",
            statHeading: "Student Progress Statistics",
            statDesc: "Track your learning development over time.",
            statTabOverview: "Overview",
            statTabKategori: "Categories",
            statTabGrafik: "Chart",
            statTotalMateri: "Materials Studied",
            statTotalQuiz: "Quizzes Completed",
            statAvgScore: "Average Score",
            statTotalMuf: "Vocabulary Learned",
            statProgress: "Progress Per Material",
            statEmpty: "No data yet. Complete a quiz to see your progress.",
            catMcq: "Text Comprehension",
            catMcqLabel: "MCQ average",
            catEssay: "Essay Skills",
            catEssayLabel: "Essay average",
            catMuf: "Vocabulary Mufradat",
            catMufLabel: "Mufradat average",
            catTotal: "Overall Score",
            catTotalLabel: "All quizzes average",
            catRekomTitle: "Improvement Recommendations",
            grafikTitle: "Score Chart Per Material",
            grafikEmpty: "No quiz data to display yet.",
            trendTitle: "Progress Trend",
            filterAll: "All",
            kosakataTitle: "Key Vocabulary",
            readInstruction: "Tap any Arabic word to see its meaning and hear its pronunciation.",
            fcFlipHint: "Tap for meaning",
            bcStat: "⑦ Statistics",
            alertFillAll: "Please fill in all fields.",
            alertNimExists: "This ID is already registered!",
            alertRegSuccess: "Registration successful! Please login.",
            alertLoginFail: "Wrong ID or Password. No account yet? Register first.",
            alertChooseMateri: "Please select a material before submitting the quiz."
        }
    }
};

window.appData = appData;
